; app/uwsgi.ini
[uwsgi]
chdir = /code
module = config.wsgi:application

# Nginx は HTTP で繋ぐ
http-socket = :3031

master = true
processes = 2
threads = 2

# 稼働・安定化
harakiri = 60
max-requests = 5000
vacuum = true
die-on-term = true
buffer-size = 8192

# (任意) ステータス確認用
stats = :9191
