; app/uwsgi.ini
[uwsgi]
chdir = /app
module = config.wsgi:application
master = true
processes = 4
threads = 2

; Nginx と接続する uwsgi ソケット（TCP）
socket = :3031
protocol = uwsgi

; 稼働・安定化
harakiri = 60
max-requests = 5000
vacuum = true
die-on-term = true
buffer-size = 8192

; (任意) uWSGI ステータス
stats = :9191
