[uwsgi]
# プロジェクトのルート（manage.py がある場所）
chdir = /code/app

# WSGI アプリ（/code/app/config/wsgi.py）
module = config.wsgi:application

# Nginx とは HTTP で会話（proxy_pass）
http-socket = :3031

master = true
processes = 2
threads = 2

# 稼働・安定化
harakiri = 60
max-requests = 5000
vacuum = true
die-on-term = true
buffer-size = 8192

# 任意（uWSGI統計）
stats = :9191
